# -*- coding: utf-8 -*-
"""Histogram.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xM7RoJ0hOHPoQ0i_8STuGm2JI6Y3Crqh
"""



import matplotlib.pyplot as plt

# Sample data: a small set of values
data = [3, 5, 2, 67, 12, 3, 5, 5, 23, 23, 14, 11, 34, 56]

# Create the histogram
plt.hist(data, bins=10, edgecolor='green')

# Set the title and labels for the plot
plt.title('Simple Histogram Example')
plt.xlabel('Numbers')
plt.ylabel('Count')

# Show the plot
plt.show()

########################################################## Task 2 ##########################################################

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

datf = pd.DataFrame({
    "Season 1": [3, 67, 5, 5, 56, 3],
    "Season 2": [12, 23, 14, 34, 34, None]
})

# Convert the DataFrame to a long format
datf_melted = datf.melt(var_name='Season', value_name='Value')

# Create the histogram with seaborn
P = sns.histplot(data=datf_melted, x='Value', hue='Season', multiple='stack')
P.set(xlabel='X Label Value', ylabel='Y Label Value')

plt.show()

########################################################## Task 3 ##########################################################

import matplotlib.pyplot as plt
import numpy as np

# Simulate data: Random ages of 1000 cancer patients (assume age between 20 and 80)
np.random.seed(42)  # For reproducibility
data = np.random.randint(20, 81, 1000)  # Generate 1000 random ages between 20 and 80

# Create a histogram
plt.hist(data, bins=15, edgecolor='black', color='skyblue')

# Set the title and labels for the plot
plt.title('Histogram of Cancer Patients Age Distribution')
plt.xlabel('Age')
plt.ylabel('Number of Patients')

# Display the plot
plt.show()

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# Sample data
data = {
    'semester': ['Sem 1', 'Sem 1', 'Sem 1', 'Sem 1', 'Sem 1', 'Sem 2', 'Sem 2', 'Sem 2', 'Sem 2', 'Sem 2'],
    'hours_studied': [5, 8, 10, 4, 6, 9, 11, 7, 12, 8]
}

# Create a DataFrame
df = pd.DataFrame(data)

# Create the boxplot
plt.figure(figsize=(8, 6))
sns.boxplot(x='semester', y='hours_studied', data=df)

# Set plot labels and title
plt.title('Student Performance: Hours Studied by Semester')
plt.xlabel('Semester')
plt.ylabel('Number of Hours Studied')

# Show plot
plt.show()

